app/Http/Controllers/ProposalDetailController.php, resources/views/estimator/form_service_additional_costs.blade.php, resources/views/estimator/form_service_equipment.blade.php, resources/views/estimator/form_service_labor.blade.php, resources/views/estimator/form_service_subcontractors.blade.php, resources/views/estimator/form_service_vehicles.blade.php, resources/views/layouts/master.blade.php
Finish Subcontractor section in estimator.
=> Finish Subcontractor section in estimator.

app/Models/ProposalDetail.php, resources/views/estimator/form_service_subcontractors.blade.php, resources/views/estimator/index.blade.php
Initialize estimator index.blade main form fields with values passed from de controller for:
- Vehicles	
- Equipment	
- Labor	
- Additional Costs	
- Sub Contractors
=> Initialize estimator index.blade main form fields with values passed from de controller

app/Http/Controllers/ProposalDetailController.php, public/js/extra-scripts.js, resources/views/estimator/_subcontractors_grid.blade.php, resources/views/estimator/form_service_subcontractors.blade.php
Update subcontractor section to allow multiples.
=> Update subcontractor section to allow multiples.

app/Http/Controllers/ProposalController.php, app/Http/Controllers/ProposalDetailController.php, app/View/Components/DeleteForm.php, resources/views/components/delete-form.blade.php, resources/views/proposals/_proposal_services.blade.php, resources/views/proposals/proposal_home.blade.php
Re-add destroy service function to ProposalDertailController.
=> Re-add destroy service function to ProposalDertailController.

app/Console/Kernel.php, app/Models/Contact.php, app/Notifications/OldProposalNotification.php, app/Providers/AppServiceProvider.php
Implemented sending Proposal Too Old notification.
=> Implemented sending Proposal Too Old notification.

app/Console/Kernel.php, app/Models/ProposalNote.php, app/Notifications/ProposalNoteNotification.php
Implemented sending proposal note reminder.
=> Implemented sending proposal note reminder.

resources/views/contacts/detailsfull.blade.php, resources/views/workorders/index.blade.php
=> Made id column clickable.

resources/views/workorders/home.blade.php
Started working in service view details.
=> Started working in service view details.

app/Http/Controllers/WorkOrderDetailsController.php, app/Http/Controllers/WorkOrderEquipmentController.php, resources/views/components/form-select.blade.php, resources/views/workorders/details.blade.php, resources/views/workorders/timesheet/entry_form.blade.php, resources/views/workorders/workorder_home.blade.php, routes/web.php
Implement timesheet section in service view details.
=> Implement timesheet section in service view details.

resources/views/workorders/subcontractor/entry_form.blade.php
Implement all five sections in service view details.
=> Implement all five sections in service view details.

app/Http/Controllers/WorkOrderDetailsController.php, resources/lang/en/translation.php, resources/lang/es/translation.php, resources/views/permit/details.blade.php, resources/views/workorders/workorder_home.blade.php
Modifying field report view for workorder service.
=> Modifying field report view for workorder service.

app/Http/Controllers/WorkOrderDetailsController.php, resources/views/workorders/equipment/_list.blade.php, resources/views/workorders/field_report.blade.php, resources/views/workorders/material/_list.blade.php, resources/views/workorders/subcontractor/_list.blade.php, resources/views/workorders/timesheet/_list.blade.php, resources/views/workorders/vehicle/_list.blade.php
Modified field report view for workorder service.
=> Modified field report view for workorder service.

app/Http/Controllers/ProposalDetailController.php, resources/views/estimator/_form_service_vehicles.blade.php, resources/views/estimator/form_service_vehicles.blade.php, routes/web.php
Modified vehicle section in estimator to add edit functionality.
=> Modified vehicle section in estimator to add edit functionality.

app/Helpers/ExceptionError.php, app/Http/Controllers/ProposalDetailController.php, resources/views/estimator/_form_service_equipment.blade.php, resources/views/estimator/form_service_equipment.blade.php, resources/views/estimator/form_service_vehicles.blade.php, routes/web.php
Modified equipment section in estimator to add edit functionality.
=> Modified equipment section in estimator to add edit functionality.

app/Http/Controllers/ProposalDetailController.php, app/Models/ProposalDetailLabor.php, resources/views/estimator/_form_service_additional_costs.blade.php, resources/views/estimator/_form_service_labor.blade.php, resources/views/estimator/form_service_additional_costs.blade.php, resources/views/estimator/form_service_equipment.blade.php, resources/views/estimator/form_service_labor.blade.php, routes/web.php
Modified labor and additional costs sections in estimator to add edit functionality.
=> Modified labor and additional costs sections in estimator to add edit functionality.

app/Http/Controllers/PermitsController.php, app/Models/County.php, resources/views/permit/create.blade.php, routes/web.php
Added county-cities reactive in create permit.
=> Added county-cities reactive in create permit.

app/Http/Controllers/PermitsController.php, app/Models/County.php, app/Models/Permit.php, resources/views/permit/create.blade.php, resources/views/permit/edit.blade.php, routes/web.php
Added county-cities reactive in edit permit.
=> Added county-cities reactive in edit permit.

app/Helpers/EnumFieldValues.php
Create helper to return field enum values from table definition.
=> Create helper to return field enum values from table definition.

app/Http/Controllers/ContactsController.php, app/Models/Contact.php, resources/views/contacts/_add_staff_form.blade.php, resources/views/contacts/detailsfull.blade.php, resources/views/contacts/index.blade.php, resources/views/layouts/master.blade.php, routes/web.php
Fix issue with add note and staff in Contact section.
=> Fix issue with add note and staff in Contact section.

app/Http/Controllers/PermitsController.php, resources/views/modals/form_select_status_modal.blade.php, resources/views/permit/index.blade.php
Fix problem with change permit status.
=> Fix problem with change permit status.

app/Http/Controllers/PermitsController.php, app/Http/Requests/PermitRequest.php, resources/views/permit/create.blade.php, resources/views/permit/edit.blade.php, resources/views/workorders/workorder_home.blade.php, routes/web.php
=> Implement add new permit.

app/Http/Controllers/WorkOrderDetailsController.php, app/Models/ProposalDetail.php, resources/lang/en/translation.php, resources/lang/es/translation.php, resources/views/workorders/view_service_accepted_subcontractor.blade.php, resources/views/workorders/view_service_additional_costs.blade.php, resources/views/workorders/view_service_subcontractors.blade.php, resources/views/workorders/view_striping.blade.php, resources/views/workorders/workorder_view_header.blade.php
Style all services from workorder with id=10680 except the stripping (Pavement Markings).
=> Style all services from workorder with id=10680 except the stripping (Pavement Markings).

app/Http/Controllers/WorkOrderDetailsController.php, app/Models/ProposalDetail.php, app/Models/ProposalDetailStripingService.php, app/Models/StripingService.php, resources/views/workorders/view_service_striping.blade.php, resources/views/workorders/view_striping.blade.php, resources/views/workorders/workorder_view_header.blade.php
Create striping view for workorders.
=> Create striping view for workorders.

app/Http/Controllers/WorkOrderDetailsController.php, app/Models/ProposalDetail.php, app/Models/ProposalDetailStripingService.php, app/Models/StripingService.php, resources/views/workorders/view_service_striping.blade.php, resources/views/workorders/view_striping.blade.php, resources/views/workorders/workorder_view_header.blade.php
Create striping view for workorders
=> Create striping view for workorders

app/Http/Controllers/ContactsController.php
Fix error when creating new contact.
=> Fix error when creating new contact.

app/Models/Proposal.php, app/Models/User.php
Assign auth user id as proposal sales person_id when auth user is a pavement consultant (role_id = 4).
=> Assign auth user id as proposal sales person_id when auth user is a pavement consultant (role_id = 4).

app/Models/WorkOrder.php
Make WorkOrder boot function public as Proposal's one.
=> Make WorkOrder boot function public as Proposal's one.

app/Http/Controllers/WorkorderFieldReportsController.php, app/Models/WorkorderFieldReport.php, app/Traits/SearchTrait.php, resources/views/workorders/field_report/details.blade.php, resources/views/workorders/field_report/index.blade.php, routes/auth_user.php
Remove duplicate route named view_service.
=> Remove duplicate route named view_service.
